// Generated by ReScript, PLEASE EDIT WITH CARE

import MainModuleScss from "./Main.module.scss";

var style = MainModuleScss;

var Dom = {
  style: style
};

export {
  Dom ,
  
}
/* style Not a pure module */
